/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Application {
    status: string;
    jobId: bigint;
    seekerId: Principal;
    message: string;
}
export interface Rating {
    revieweeId: Principal;
    reviewerId: Principal;
    score: bigint;
    comment: string;
    timestamp: bigint;
}
export interface Analytics {
    totalSeekers: bigint;
    totalJobs: bigint;
    averageRating: number;
    totalPosters: bigint;
    totalApplications: bigint;
}
export interface JobFilter {
    jobType?: string;
    minPay?: bigint;
    keyword?: string;
    maxPay?: bigint;
    skills?: Array<string>;
    location?: string;
}
export interface SeekerProfile {
    id: Principal;
    bio: string;
    name: string;
    qualifications: Array<string>;
    available: boolean;
    experience: string;
    portfolioUrl: string;
    skills: Array<string>;
}
export interface JobListing {
    id: bigint;
    pay: bigint;
    title: string;
    active: boolean;
    postedBy: Principal;
    jobType: string;
    description: string;
    timestamp: bigint;
    requiredSkills: Array<string>;
    location: string;
}
export interface PosterProfile {
    id: Principal;
    verified: boolean;
    contactInfo: string;
    name: string;
    companyName: string;
}
export interface UserProfile {
    name: string;
    role: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminApproveJobListing(jobId: bigint): Promise<void>;
    adminGetAnalytics(): Promise<Analytics>;
    adminListJobListings(): Promise<Array<JobListing>>;
    adminListPosters(): Promise<Array<PosterProfile>>;
    adminListSeekers(): Promise<Array<SeekerProfile>>;
    adminRemoveJobListing(jobId: bigint): Promise<void>;
    adminVerifyPoster(posterId: Principal): Promise<void>;
    applyToJob(jobId: bigint, message: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createJobListing(title: string, description: string, requiredSkills: Array<string>, location: string, pay: bigint, jobType: string): Promise<bigint>;
    createPosterProfile(name: string, companyName: string, contactInfo: string): Promise<void>;
    createSeekerProfile(name: string, bio: string, skills: Array<string>, qualifications: Array<string>, experience: string, portfolioUrl: string): Promise<void>;
    getApplicationsForJob(jobId: bigint): Promise<Array<Application>>;
    getAverageRatingForUser(userId: Principal): Promise<number>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJobListing(id: bigint): Promise<JobListing | null>;
    getMatchedJobsForSeeker(seekerId: Principal): Promise<Array<JobListing>>;
    getMyApplications(): Promise<Array<Application>>;
    getPosterProfile(id: Principal): Promise<PosterProfile | null>;
    getRatingsForUser(userId: Principal): Promise<Array<Rating>>;
    getSeekerProfile(id: Principal): Promise<SeekerProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchJobs(filter: JobFilter): Promise<Array<JobListing>>;
    submitRating(revieweeId: Principal, score: bigint, comment: string): Promise<void>;
    updateApplicationStatus(jobId: bigint, seekerId: Principal, newStatus: string): Promise<void>;
    updateJobListingStatus(jobId: bigint, active: boolean): Promise<void>;
    updateSeekerAvailability(available: boolean): Promise<void>;
}
import type { JobFilter as _JobFilter, JobListing as _JobListing, PosterProfile as _PosterProfile, SeekerProfile as _SeekerProfile, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminApproveJobListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveJobListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveJobListing(arg0);
            return result;
        }
    }
    async adminGetAnalytics(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAnalytics();
            return result;
        }
    }
    async adminListJobListings(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListJobListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListJobListings();
            return result;
        }
    }
    async adminListPosters(): Promise<Array<PosterProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListPosters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListPosters();
            return result;
        }
    }
    async adminListSeekers(): Promise<Array<SeekerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListSeekers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListSeekers();
            return result;
        }
    }
    async adminRemoveJobListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveJobListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveJobListing(arg0);
            return result;
        }
    }
    async adminVerifyPoster(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminVerifyPoster(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminVerifyPoster(arg0);
            return result;
        }
    }
    async applyToJob(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToJob(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createJobListing(arg0: string, arg1: string, arg2: Array<string>, arg3: string, arg4: bigint, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobListing(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobListing(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createPosterProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPosterProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPosterProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async createSeekerProfile(arg0: string, arg1: string, arg2: Array<string>, arg3: Array<string>, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSeekerProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSeekerProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async getApplicationsForJob(arg0: bigint): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsForJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsForJob(arg0);
            return result;
        }
    }
    async getAverageRatingForUser(arg0: Principal): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRatingForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRatingForUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobListing(arg0: bigint): Promise<JobListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobListing(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobListing(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchedJobsForSeeker(arg0: Principal): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchedJobsForSeeker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchedJobsForSeeker(arg0);
            return result;
        }
    }
    async getMyApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications();
            return result;
        }
    }
    async getPosterProfile(arg0: Principal): Promise<PosterProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosterProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosterProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatingsForUser(arg0: Principal): Promise<Array<Rating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingsForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingsForUser(arg0);
            return result;
        }
    }
    async getSeekerProfile(arg0: Principal): Promise<SeekerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeekerProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeekerProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchJobs(arg0: JobFilter): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJobs(to_candid_JobFilter_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJobs(to_candid_JobFilter_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitRating(arg0: Principal, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRating(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRating(arg0, arg1, arg2);
            return result;
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateJobListingStatus(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobListingStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobListingStatus(arg0, arg1);
            return result;
        }
    }
    async updateSeekerAvailability(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSeekerAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSeekerAvailability(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobListing]): JobListing | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PosterProfile]): PosterProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SeekerProfile]): SeekerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_JobFilter_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobFilter): _JobFilter {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jobType?: string;
    minPay?: bigint;
    keyword?: string;
    maxPay?: bigint;
    skills?: Array<string>;
    location?: string;
}): {
    jobType: [] | [string];
    minPay: [] | [bigint];
    keyword: [] | [string];
    maxPay: [] | [bigint];
    skills: [] | [Array<string>];
    location: [] | [string];
} {
    return {
        jobType: value.jobType ? candid_some(value.jobType) : candid_none(),
        minPay: value.minPay ? candid_some(value.minPay) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none(),
        maxPay: value.maxPay ? candid_some(value.maxPay) : candid_none(),
        skills: value.skills ? candid_some(value.skills) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
