/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'totalSeekers' : bigint,
  'totalJobs' : bigint,
  'averageRating' : number,
  'totalPosters' : bigint,
  'totalApplications' : bigint,
}
export interface Application {
  'status' : string,
  'jobId' : bigint,
  'seekerId' : Principal,
  'message' : string,
}
export interface JobFilter {
  'jobType' : [] | [JobType],
  'minPay' : [] | [bigint],
  'keyword' : [] | [string],
  'maxPay' : [] | [bigint],
  'skills' : [] | [Array<string>],
  'location' : [] | [string],
}
export interface JobListing {
  'id' : bigint,
  'pay' : bigint,
  'title' : string,
  'active' : boolean,
  'postedBy' : Principal,
  'jobType' : JobType,
  'description' : string,
  'timestamp' : bigint,
  'requiredSkills' : Array<string>,
  'location' : string,
}
export type JobType = { 'nysc' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null } |
  { 'artisan' : null } |
  { 'shortTerm' : null };
export interface PosterProfile {
  'id' : Principal,
  'verified' : boolean,
  'contactInfo' : string,
  'name' : string,
  'companyName' : string,
}
export interface Rating {
  'revieweeId' : Principal,
  'reviewerId' : Principal,
  'score' : bigint,
  'comment' : string,
  'timestamp' : bigint,
}
export interface SeekerProfile {
  'id' : Principal,
  'bio' : string,
  'name' : string,
  'qualifications' : Array<string>,
  'available' : boolean,
  'experience' : string,
  'portfolioUrl' : string,
  'skills' : Array<string>,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminApproveJobListing' : ActorMethod<[bigint], undefined>,
  'adminGetAnalytics' : ActorMethod<[], Analytics>,
  'adminListJobListings' : ActorMethod<[], Array<JobListing>>,
  'adminListPosters' : ActorMethod<[], Array<PosterProfile>>,
  'adminListSeekers' : ActorMethod<[], Array<SeekerProfile>>,
  'adminRemoveJobListing' : ActorMethod<[bigint], undefined>,
  'adminVerifyPoster' : ActorMethod<[Principal], undefined>,
  'applyToJob' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJobListing' : ActorMethod<
    [string, string, Array<string>, string, bigint, JobType],
    bigint
  >,
  'createPosterProfile' : ActorMethod<[string, string, string], undefined>,
  'createSeekerProfile' : ActorMethod<
    [string, string, Array<string>, Array<string>, string, string],
    undefined
  >,
  'getApplicationsForJob' : ActorMethod<[bigint], Array<Application>>,
  'getAverageRatingForUser' : ActorMethod<[Principal], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobListing' : ActorMethod<[bigint], [] | [JobListing]>,
  'getMatchedJobsForSeeker' : ActorMethod<[Principal], Array<JobListing>>,
  'getMyApplications' : ActorMethod<[], Array<Application>>,
  'getPosterProfile' : ActorMethod<[Principal], [] | [PosterProfile]>,
  'getRatingsForUser' : ActorMethod<[Principal], Array<Rating>>,
  'getSeekerProfile' : ActorMethod<[Principal], [] | [SeekerProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchJobs' : ActorMethod<[JobFilter], Array<JobListing>>,
  'submitRating' : ActorMethod<[Principal, bigint, string], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, Principal, string],
    undefined
  >,
  'updateJobListingStatus' : ActorMethod<[bigint, boolean], undefined>,
  'updateSeekerAvailability' : ActorMethod<[boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];