/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Analytics = IDL.Record({
  'totalSeekers' : IDL.Nat,
  'totalJobs' : IDL.Nat,
  'averageRating' : IDL.Float64,
  'totalPosters' : IDL.Nat,
  'totalApplications' : IDL.Nat,
});
export const JobType = IDL.Variant({
  'nysc' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
  'artisan' : IDL.Null,
  'shortTerm' : IDL.Null,
});
export const JobListing = IDL.Record({
  'id' : IDL.Nat,
  'pay' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'postedBy' : IDL.Principal,
  'jobType' : JobType,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'requiredSkills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const PosterProfile = IDL.Record({
  'id' : IDL.Principal,
  'verified' : IDL.Bool,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'companyName' : IDL.Text,
});
export const SeekerProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'qualifications' : IDL.Vec(IDL.Text),
  'available' : IDL.Bool,
  'experience' : IDL.Text,
  'portfolioUrl' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AdvertisementPlacement = IDL.Variant({
  'jobBoard' : IDL.Null,
  'jobDetail' : IDL.Null,
  'posterDashboard' : IDL.Null,
  'seekerDashboard' : IDL.Null,
  'landing' : IDL.Null,
});
export const Advertisement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'expiresAt' : IDL.Opt(IDL.Int),
  'linkUrl' : IDL.Text,
  'placement' : AdvertisementPlacement,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'image' : ExternalBlob,
});
export const Application = IDL.Record({
  'status' : IDL.Text,
  'jobId' : IDL.Nat,
  'seekerId' : IDL.Principal,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Rating = IDL.Record({
  'revieweeId' : IDL.Principal,
  'reviewerId' : IDL.Principal,
  'score' : IDL.Nat,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const JobFilter = IDL.Record({
  'jobType' : IDL.Opt(JobType),
  'minPay' : IDL.Opt(IDL.Nat),
  'keyword' : IDL.Opt(IDL.Text),
  'maxPay' : IDL.Opt(IDL.Nat),
  'skills' : IDL.Opt(IDL.Vec(IDL.Text)),
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminApproveJobListing' : IDL.Func([IDL.Nat], [], []),
  'adminGetAnalytics' : IDL.Func([], [Analytics], ['query']),
  'adminListJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'adminListPosters' : IDL.Func([], [IDL.Vec(PosterProfile)], ['query']),
  'adminListSeekers' : IDL.Func([], [IDL.Vec(SeekerProfile)], ['query']),
  'adminRemoveJobListing' : IDL.Func([IDL.Nat], [], []),
  'adminVerifyPoster' : IDL.Func([IDL.Principal], [], []),
  'applyToJob' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAd' : IDL.Func(
      [
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        AdvertisementPlacement,
        IDL.Opt(IDL.Int),
      ],
      [IDL.Nat],
      [],
    ),
  'createJobListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat, JobType],
      [IDL.Nat],
      [],
    ),
  'createPosterProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createSeekerProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteAd' : IDL.Func([IDL.Nat], [], []),
  'getAdsByPlacement' : IDL.Func(
      [AdvertisementPlacement],
      [IDL.Vec(Advertisement)],
      ['query'],
    ),
  'getApplicationsForJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'getAverageRatingForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Float64],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobListing' : IDL.Func([IDL.Nat], [IDL.Opt(JobListing)], ['query']),
  'getMatchedJobsForSeeker' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getPosterProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PosterProfile)],
      ['query'],
    ),
  'getRatingsForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Rating)], ['query']),
  'getSeekerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SeekerProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchJobs' : IDL.Func([JobFilter], [IDL.Vec(JobListing)], ['query']),
  'submitRating' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'toggleAdActive' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateAd' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        AdvertisementPlacement,
        IDL.Opt(IDL.Int),
      ],
      [],
      [],
    ),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Nat, IDL.Principal, IDL.Text],
      [],
      [],
    ),
  'updateJobListingStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateSeekerAvailability' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Analytics = IDL.Record({
    'totalSeekers' : IDL.Nat,
    'totalJobs' : IDL.Nat,
    'averageRating' : IDL.Float64,
    'totalPosters' : IDL.Nat,
    'totalApplications' : IDL.Nat,
  });
  const JobType = IDL.Variant({
    'nysc' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
    'artisan' : IDL.Null,
    'shortTerm' : IDL.Null,
  });
  const JobListing = IDL.Record({
    'id' : IDL.Nat,
    'pay' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'postedBy' : IDL.Principal,
    'jobType' : JobType,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const PosterProfile = IDL.Record({
    'id' : IDL.Principal,
    'verified' : IDL.Bool,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'companyName' : IDL.Text,
  });
  const SeekerProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'qualifications' : IDL.Vec(IDL.Text),
    'available' : IDL.Bool,
    'experience' : IDL.Text,
    'portfolioUrl' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AdvertisementPlacement = IDL.Variant({
    'jobBoard' : IDL.Null,
    'jobDetail' : IDL.Null,
    'posterDashboard' : IDL.Null,
    'seekerDashboard' : IDL.Null,
    'landing' : IDL.Null,
  });
  const Advertisement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'expiresAt' : IDL.Opt(IDL.Int),
    'linkUrl' : IDL.Text,
    'placement' : AdvertisementPlacement,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'image' : ExternalBlob,
  });
  const Application = IDL.Record({
    'status' : IDL.Text,
    'jobId' : IDL.Nat,
    'seekerId' : IDL.Principal,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Rating = IDL.Record({
    'revieweeId' : IDL.Principal,
    'reviewerId' : IDL.Principal,
    'score' : IDL.Nat,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const JobFilter = IDL.Record({
    'jobType' : IDL.Opt(JobType),
    'minPay' : IDL.Opt(IDL.Nat),
    'keyword' : IDL.Opt(IDL.Text),
    'maxPay' : IDL.Opt(IDL.Nat),
    'skills' : IDL.Opt(IDL.Vec(IDL.Text)),
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminApproveJobListing' : IDL.Func([IDL.Nat], [], []),
    'adminGetAnalytics' : IDL.Func([], [Analytics], ['query']),
    'adminListJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'adminListPosters' : IDL.Func([], [IDL.Vec(PosterProfile)], ['query']),
    'adminListSeekers' : IDL.Func([], [IDL.Vec(SeekerProfile)], ['query']),
    'adminRemoveJobListing' : IDL.Func([IDL.Nat], [], []),
    'adminVerifyPoster' : IDL.Func([IDL.Principal], [], []),
    'applyToJob' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAd' : IDL.Func(
        [
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          AdvertisementPlacement,
          IDL.Opt(IDL.Int),
        ],
        [IDL.Nat],
        [],
      ),
    'createJobListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat, JobType],
        [IDL.Nat],
        [],
      ),
    'createPosterProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createSeekerProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteAd' : IDL.Func([IDL.Nat], [], []),
    'getAdsByPlacement' : IDL.Func(
        [AdvertisementPlacement],
        [IDL.Vec(Advertisement)],
        ['query'],
      ),
    'getApplicationsForJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getAverageRatingForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Float64],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobListing' : IDL.Func([IDL.Nat], [IDL.Opt(JobListing)], ['query']),
    'getMatchedJobsForSeeker' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getPosterProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PosterProfile)],
        ['query'],
      ),
    'getRatingsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Rating)],
        ['query'],
      ),
    'getSeekerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SeekerProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchJobs' : IDL.Func([JobFilter], [IDL.Vec(JobListing)], ['query']),
    'submitRating' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'toggleAdActive' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateAd' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          AdvertisementPlacement,
          IDL.Opt(IDL.Int),
        ],
        [],
        [],
      ),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Nat, IDL.Principal, IDL.Text],
        [],
        [],
      ),
    'updateJobListingStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateSeekerAvailability' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };